### ISSUE TITLE
How to generate prepare initial files by myself?

### ISSUE THREAD

**Issue by woxue** [zhangxinyu-xyz/PAST-ReID#7]
Thanks for your excellent work!
Can you tell me how to generate prepare initial files (i.e.  D-M_M-t-feature.mat  and D-M_M-t-rerank-distmat.mat) by myself?
I want to try this method with some new archs.
Thank you~

**Comment by zhangxinyu-xyz** [comment]
@woxue You can directly train the PCB model on Duke (in PCB project). Then extract the features of training images on Market1501 to get D-M_M-t-feature.mat. After that, you can conduct rerank (in our project or rerank project https://github.com/zhunzhong07/person-re-ranking) to get D-M_M-t-rerank-distmat.mat

**Comment by woxue** [comment]
Thank you!
